First page/create first page by html and css
MalakAyyash/Training-Tasks pull request #1
Opened 2023-08-09 09:00 UTC by MalakAyyash

2023-08-09 09:11 UTC, MalakAyyash commented on main.html
> +
please revmove extra lines

2023-08-09 09:13 UTC, MuathYHKefayah commented on main.html
> +
remove an extra lines please

2023-08-09 09:15 UTC, MuathYHKefayah requested changes

2023-08-09 09:15 UTC, MuathYHKefayah commented on main.html
> +
test

2023-08-13 06:48 UTC, MuathYHKefayah commented on css/style.css
> +}
Great work!

2023-08-13 06:48 UTC, MuathYHKefayah commented on index.html
> +</html>
Well done!

2023-08-13 08:12 UTC, MuathYHKefayah approved these changes

2023-08-13 08:18 UTC, merged